'use client';

import { useParams, notFound, useRouter } from 'next/navigation';
import Link from 'next/link';
import { mockContacts, mockNotes, mockEmails, mockCalls, allActivities } from '@/lib/data';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  ChevronLeft,
  User,
  Building2,
  Mail,
  Phone,
  Briefcase,
  BrainCircuit,
  FileText,
  Activity,
  CalendarDays,
  MoreVertical,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Separator } from '@/components/ui/separator';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { format, formatDistanceToNow } from 'date-fns';
import { de } from 'date-fns/locale';
import { ScrollArea } from '@/components/ui/scroll-area';

const KiGedaechtnis = ({ contact }: { contact: any }) => {
    // This is mock data, in a real app this would be generated by an AI
    const memory = {
        summary: `Kunde seit 2 Jahren, primär an Datenanalyse-Software interessiert. Kommuniziert bevorzugt per E-Mail, reagiert schnell auf konkrete Angebote.`,
        insights: [
            "Wiederkehrendes Thema: Skalierbarkeit der Lösung.",
            "Typischer Einwand: Budget für das laufende Quartal ist knapp.",
            "Entscheidet nach technischer Demo und klarem ROI.",
        ],
        relationshipStatus: "Aktiv",
        statusReason: "Regelmäßiger Austausch, letzter Kontakt vor 2 Tagen.",
        strategy: "Proaktive Kommunikation mit Fokus auf ROI und langfristigen Nutzen. Formelle, aber freundliche Ansprache."
    };

    return (
        <Card className="bg-blue-950/50 border-blue-500/20">
            <CardHeader>
                <CardTitle className="text-base text-blue-300 flex items-center gap-2">
                    <BrainCircuit className="w-5 h-5"/>
                    KI-Gedächtnis
                </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
                <div>
                    <h4 className="font-bold text-blue-300/80 text-xs uppercase">Kurzprofil</h4>
                    <p className="text-blue-300/90">{memory.summary}</p>
                </div>
                 <div>
                    <h4 className="font-bold text-blue-300/80 text-xs uppercase">Wichtige Erkenntnisse</h4>
                    <ul className="list-disc pl-5 text-blue-300/90">
                        {memory.insights.map((item, i) => <li key={i}>{item}</li>)}
                    </ul>
                </div>
                 <div>
                    <h4 className="font-bold text-blue-300/80 text-xs uppercase">Beziehungsstatus</h4>
                    <p className="font-bold text-blue-200">{memory.relationshipStatus} <span className="font-normal text-blue-300/80">({memory.statusReason})</span></p>
                </div>
                 <div>
                    <h4 className="font-bold text-blue-300/80 text-xs uppercase">Empfohlene Strategie</h4>
                    <p className="text-blue-300/90">{memory.strategy}</p>
                </div>
                <p className="text-[10px] text-blue-500/60 italic pt-2 border-t border-blue-500/20">Zusammenfassung basierend auf Daten der letzten 6 Monate. Letzte Aktualisierung: Heute.</p>
            </CardContent>
        </Card>
    )
}

export default function ContactDetailPage() {
  const params = useParams();
  const router = useRouter();
  const contactId = params.contactId as string;
  const contact = mockContacts.find((c) => c.id.toString() === contactId);

  if (!contact) {
    notFound();
  }

  const relatedNotes = mockNotes.filter(n => n.contextName === contact.name || n.content.includes(contact.name));
  const relatedEmails = mockEmails.filter(e => e.contactName === contact.name);
  const relatedCalls = mockCalls.filter(c => c.contactName === contact.name);

  return (
    <div className="space-y-6">
      <header>
        <Button variant="ghost" onClick={() => router.back()} className="mb-2 h-auto p-0 text-sm text-muted-foreground hover:text-foreground">
            <ChevronLeft className="w-4 h-4 mr-1" />
            Zurück zur Kontaktübersicht
        </Button>
        <div className="flex justify-between items-center">
            <div className="flex items-center gap-4">
                <Avatar className="w-16 h-16 text-2xl">
                    <AvatarFallback>{contact.name.split(' ').map(n => n[0]).join('')}</AvatarFallback>
                </Avatar>
                <div>
                    <h1 className="text-2xl font-bold text-foreground">{contact.name}</h1>
                    <p className="text-muted-foreground">{contact.company}</p>
                </div>
            </div>
            <div className="flex items-center gap-2">
                <Button variant="outline">Nachricht</Button>
                <Button>Aktion hinzufügen</Button>
            </div>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
        <div className="lg:col-span-1 space-y-6">
            <Card>
                <CardHeader><CardTitle className="text-base">Kontaktinformationen</CardTitle></CardHeader>
                <CardContent className="space-y-3 text-sm">
                    <p className="flex items-center gap-2"><Mail className="w-4 h-4 text-muted-foreground"/> {contact.email}</p>
                    <p className="flex items-center gap-2"><Building2 className="w-4 h-4 text-muted-foreground"/> {contact.company}</p>
                    <Separator/>
                    <p className="flex items-center gap-2"><User className="w-4 h-4 text-muted-foreground"/> Zuständig: {contact.owner}</p>
                    <p className="flex items-center gap-2"><Briefcase className="w-4 h-4 text-muted-foreground"/> Phase: <Badge variant="outline">{contact.leadStatus}</Badge></p>
                </CardContent>
            </Card>
            <KiGedaechtnis contact={contact} />
        </div>
        <div className="lg:col-span-2">
            <Tabs defaultValue="activities">
                <TabsList>
                    <TabsTrigger value="activities">Aktivitäten</TabsTrigger>
                    <TabsTrigger value="notes">Notizen</TabsTrigger>
                    <TabsTrigger value="emails">E-Mails</TabsTrigger>
                    <TabsTrigger value="calls">Anrufe</TabsTrigger>
                </TabsList>
                <Card className="mt-4">
                    <ScrollArea className="h-[600px]">
                        <TabsContent value="activities" className="m-0 p-4">
                             <div className="space-y-4">
                                {allActivities.filter(a => a.context.includes(contact.name)).map(activity => (
                                    <div key={activity.id} className="flex items-center gap-3 text-sm">
                                        <div className="p-2 bg-muted rounded-full"><Activity className="w-4 h-4 text-muted-foreground"/></div>
                                        <div>
                                            <p className="font-medium text-foreground">{activity.description}</p>
                                            <p className="text-xs text-muted-foreground">{format(activity.dueDate, "dd.MM.yyyy")}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </TabsContent>
                        <TabsContent value="notes" className="m-0 p-4">
                            <div className="space-y-4">
                                {relatedNotes.map(note => (
                                    <div key={note.id} className="text-sm">
                                        <p className="font-bold">{note.title}</p>
                                        <p className="text-muted-foreground">{note.content}</p>
                                        <p className="text-xs text-muted-foreground/50 mt-1">{format(new Date(note.createdAt), "dd.MM.yyyy")} - {note.createdBy}</p>
                                    </div>
                                ))}
                            </div>
                        </TabsContent>
                        <TabsContent value="emails" className="m-0 p-4">
                           <div className="space-y-4">
                                {relatedEmails.map(email => (
                                    <div key={email.id} className="text-sm">
                                        <p className="font-bold">{email.subject}</p>
                                        <p className="text-xs text-muted-foreground mt-1">{formatDistanceToNow(new Date(email.createdAt), { addSuffix: true, locale: de })}</p>
                                    </div>
                                ))}
                            </div>
                        </TabsContent>
                        <TabsContent value="calls" className="m-0 p-4">
                             <div className="space-y-4">
                                {relatedCalls.map(call => (
                                    <div key={call.id} className="text-sm">
                                        <p className="font-bold">{call.type} ({call.duration})</p>
                                        <p className="text-muted-foreground">Status: {call.status}</p>
                                        <p className="text-xs text-muted-foreground mt-1">{formatDistanceToNow(new Date(call.createdAt), { addSuffix: true, locale: de })}</p>
                                    </div>
                                ))}
                            </div>
                        </TabsContent>
                    </ScrollArea>
                </Card>
            </Tabs>
        </div>
      </div>
    </div>
  );
}
